import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import{AiFillLinkedin} from 'react-icons/ai';
import Image from "next/image";
import myIcon from "/Users/scottmcnally/Developer/Personal Projects/React Portfolio Website/portfolio-website/public/myIcon.png";
import flashcards from "/Users/scottmcnally/Developer/Personal Projects/React Portfolio Website/portfolio-website/public/flashcards.png";
import helphome from "/Users/scottmcnally/Developer/Personal Projects/React Portfolio Website/portfolio-website/public/help@home.png";
import portfolio from "/Users/scottmcnally/Developer/Personal Projects/React Portfolio Website/portfolio-website/public/portfolio.jpeg";
import rally from "/Users/scottmcnally/Developer/Personal Projects/React Portfolio Website/portfolio-website/public/rally.png";
import swift from "/Users/scottmcnally/Developer/Personal Projects/React Portfolio Website/portfolio-website/public/swift.png";
import java from "/Users/scottmcnally/Developer/Personal Projects/React Portfolio Website/portfolio-website/public/java.png";
import web from "/Users/scottmcnally/Developer/Personal Projects/React Portfolio Website/portfolio-website/public/web.png"
import python from "/Users/scottmcnally/Developer/Personal Projects/React Portfolio Website/portfolio-website/public/python.png";
import { useState } from 'react';
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Scott McNally</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 mx-auto md:px-20 lg:px-40 dark:bg-gray-700'>
        <section className = "min-h-screen">
          <nav className='flex justify-between py-10 mb-5'>
            <h1 className='text-lg md:text-xl font-burtons sdark:text-white'>Scott McNally</h1>
            <ul className='flex items-center'>
              <li className=' cursor-pointer text-white bg-gradient-to-r from-cyan-500 to-teal-500 p-2 rounded-full text-base md:text-xl'><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}/></li>
              <li className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-4 text-xs md:text-base'><a href="/Resume.pdf">Resume</a></li>
            </ul>
          </nav>
          <div className='relative mx-auto w-40 h-40 bg-gradient-to-b from-gray-300 to-teal-300 rounded-full shadow-2xl md:h-64 md:w-64'>
            <Image src={myIcon} className='rounded-full h-full w-full object-cover object-center border-transparent border-4' alt="image"/>
          </div>
          <div className='text-center pb-10 pt-5'>
            <h2 className='font-extrabold text-transparent text-4xl md:text-5xl bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600 p-4'>Scott McNally</h2>
            <p className='font-bold text-sm md:text-lg dark:text-white'>Computer Science Student based in Dublin, Ireland</p>
          </div>
          <div className='flex justify-center  mb-5'>
            <div className=' text-base md:text-xl bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md'>
              <h3 className='font-bold '>About Me</h3>
            </div>

          </div>
          <div className='flex justify-center mb-5'>
            <div className='md:text-4xl text-3xl flex justify-center text-white bg-gradient-to-r from-gray-400 to-gray-500 px-4 py-2 rounded-md md:w-56'>
              <AiFillLinkedin/>
              <h3 className='md:text-xl text-base py-1 px-2 font-bold'><a href='https://www.linkedin.com/in/scottamcnally'>Get in Touch</a></h3>
            </div>
          </div>
        </section>
        <section className='min-h-screen '>
          <h3 className='text-2xl font-burtons py-1 dark:text-white text-center'>About Me</h3>
          <p className='text-sm md:text-base p-4 text-gray-800 m-1 mb-2 dark:text-gray-200 shadow-2xl text-center rounded-3xl max-w-xl mx-auto'>
            I am currently studying Computer Science in <span className='text-pink-400 font-bold'>Trinity College
            Dublin</span> in the class of 2027. As a part of my studies, I do a 
            lot of work using <span className='text-pink-400 font-bold'>Java</span> and am learning to use it in a wide
            area of applications. Alongside my college course, I enjoy
            creating apps using the <span className='text-pink-400 font-bold'>Swift Programming Language</span> and 
            making websites with modern tools such as <span className='text-pink-400 font-bold'>React and CSS tailwind</span>.<br/>
            I also taught myself <span className='text-pink-400 font-bold'>Python</span> while in secondary school. I used
            this to recreate Mathematical concepts such as Conway's Game
            Of Life and other projects. <br/>
            I really enjoy learning new things and aquiring new skills.

          </p>
          <div className='text-center rounded-3xl shadow-2xl p-5 mb-8 max-w-xl mx-auto '>
            <h3 className='text-xl md:text-2xl py-5 font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600'>I have experience with:</h3>
            <div className='flex justify-center text-lg bg-gradient-to-r from-orange-400 to-orange-600 text-white w-48 mx-auto rounded-lg mb-3'>
              <Image src={swift} className="h-5 w-5 my-auto mr-2" alt="image"/>
              <p className=' font-bold py-2'>Swift</p>
            </div>
            <div className='flex justify-center text-lg bg-gradient-to-r from-red-500 to-red-700 text-white w-48 mx-auto rounded-lg mb-3'>
              <Image src={java} className="h-5 w-7 my-auto mr-2" alt="image"/>
              <p className=' font-bold py-2'>Java</p>
            </div>
            <div className='flex justify-center text-lg bg-gradient-to-r from-blue-600 to-blue-800 text-white w-48 mx-auto rounded-lg mb-3'>
              <Image src={python} className="h-5 w-5 my-auto mr-2" alt="image"/>
              <p className=' font-bold py-2'>Python</p>
            </div>
            <div className='flex justify-center text-lg bg-gradient-to-r from-cyan-500 to-cyan-700 text-white w-48 mx-auto rounded-lg mb-3'>
              <Image src={web} className="h-5 w-5 my-auto mr-2" alt="image"/>
              <p className=' font-bold py-2'>Web Dev</p>
            </div>

          </div>
        </section>
        <section className='min-h-screen'>
          <h3 className='text-2xl font-burtons py-1 dark:text-white text-center'>Portfolio</h3>
          <p className='text-sm md:text-base p-4 text-gray-800 m-1 mb-2 dark:text-gray-200 shadow-2xl text-center rounded-3xl max-w-xl mx-auto'>
            The following are a range of projects which I have done using 
            the languages listed above.

          </p>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1 max-w-sm mx-auto relative'>
              <h2 className=' absolute top-3 left-4 z-50  bg-gradient-to-r from-purple-400 to-pink-600 text-white p-2 rounded-xl'>RallyNavigator App</h2>
              <Image src={rally} className='rounded-3xl object-cover opacity-80 shadow-2xl'  width={'100%'} height={'100%'} alt="image"/>
            </div>
            <div className='basis-1/3 flex-1 max-w-sm mx-auto relative'>
            <h2 className=' absolute top-3 left-4 z-50  bg-gradient-to-r from-purple-400 to-pink-600 text-white p-2 rounded-xl'>Flashcards App</h2>
              <Image src={flashcards} className='rounded-3xl object-cover opacity-80 shadow-2xl' width={'100%'} height={'100%'} alt="image"/>
            </div>
            <div className='basis-1/3 flex-1 max-w-sm mx-auto relative'>
            <h2 className=' absolute top-3 left-4 z-50  bg-gradient-to-r from-purple-400 to-pink-600 text-white p-2 rounded-xl'>Elderly Reminder System</h2>
              <Image src={helphome} className='rounded-3xl object-cover opacity-80 shadow-2xl' width={'100%'} height={'100%'} alt="image"/>
            </div>
            <div className='basis-1/3 flex-1 max-w-sm mx-auto relative'>
            <h2 className=' absolute top-3 left-4 z-50  bg-gradient-to-r from-purple-400 to-pink-600 text-white p-2 rounded-xl'>Portfolio Website</h2>
              <Image src={portfolio} className='rounded-3xl object-cover opacity-80 shadow-2xl' width={'100%'} height={'100%'} alt="image"/>
            </div>
          </div>
        </section>

      </main>
    </div>
  );
}
